FROM nginx:alpine
COPY . /usr/share/nginx/html

# docker-machine start docker
# eval "$(docker-machine env docker)"
# source ~/.zshrc
# docker build -t todolist .
# docker-machine ip docker
# docker run -d -p 80:80 todolist
#