#!/bin/bash
#1. start Alpine with this command "docker run -it --rm alpine"
docker run -it --rm alpine

# 2. Run this command in Alpine to install vim
apk update && apk add vim

# 3. Use this command to initiate Vim
vim
